import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

export const metadata = {
  title: "Disclaimer – Smart Energy Management",
  description:
    "Important information about the accuracy and limitations of our electricity bill estimation tool.",
};

// ─────────────────────────────────────────────
// Data
// ─────────────────────────────────────────────

const disclaimerCards = [
  {
    icon: (
      <svg className="h-5 w-5 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        <path d="M12 8v4M12 16h.01" />
      </svg>
    ),
    title: "Estimates Only",
    description:
      "All electricity bill figures generated by this tool are estimates. They are not a guarantee, quote, or official calculation from any utility provider.",
  },
  {
    icon: (
      <svg className="h-5 w-5 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
      </svg>
    ),
    title: "Regional Variation",
    description:
      "Electricity tariffs, slab rates, and taxes vary significantly by region, provider, and time of year. Always verify rates with your local utility company.",
  },
  {
    icon: (
      <svg className="h-5 w-5 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="2" y="7" width="20" height="14" rx="2" />
        <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2" />
        <line x1="12" y1="12" x2="12" y2="16" />
        <line x1="10" y1="14" x2="14" y2="14" />
      </svg>
    ),
    title: "No Professional Advice",
    description:
      "Nothing on this platform constitutes professional energy consulting, financial, or engineering advice. Consult a qualified professional for binding assessments.",
  },
  {
    icon: (
      <svg className="h-5 w-5 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
        <polyline points="14 2 14 8 20 8" />
        <line x1="16" y1="13" x2="8" y2="13" />
        <line x1="16" y1="17" x2="8" y2="17" />
      </svg>
    ),
    title: "Data Accuracy",
    description:
      "Results depend entirely on the appliance data you enter. Inaccurate wattage or usage hours will produce inaccurate estimates. Verify appliance specs from manufacturer labels.",
  },
];

const sections = [
  {
    id: "general-disclaimer",
    num: "01",
    title: "General Disclaimer",
    content:
      "The information and tools provided on this website are for general informational and educational purposes only. While we strive to keep the electricity bill estimates as accurate and up to date as possible, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the calculator results or related information. Any reliance you place on such information is therefore strictly at your own risk.",
  },
  {
    id: "estimation-accuracy",
    num: "02",
    title: "Estimation Accuracy & Limitations",
    content:
      "Our calculator uses generalised appliance wattage values and publicly available electricity slab rates to produce estimates. Actual electricity consumption and bills may differ due to appliance age and efficiency ratings, voltage fluctuations, power factor variations, standby and idle power draw, seasonal and environmental conditions, utility company billing adjustments, taxes, surcharges, and fuel price adjustments. Always refer to your official utility bill or meter readings for definitive figures.",
  },
  {
    id: "tariff-rates",
    num: "03",
    title: "Tariff Rates & Slab Information",
    content:
      "Electricity tariff rates used in this tool are based on the latest publicly available data at the time of development. These rates are subject to change by government authorities and utility companies at any time without prior notice. We do not guarantee that the rates used in our calculations reflect the current tariffs applicable to your specific connection type, region, or utility provider. Users are strongly advised to verify current rates directly with their electricity provider or the relevant regulatory authority.",
  },
  {
    id: "no-liability",
    num: "04",
    title: "Limitation of Liability",
    content:
      "To the fullest extent permitted by applicable law, we exclude all liability for any loss or damage of any nature arising in connection with your use of this website and calculator, including but not limited to direct, indirect, incidental, punitive, and consequential damages. This includes any financial decisions made based on the estimates produced by our tool. We shall not be liable for any errors or omissions in the content of this site or for any losses incurred as a result of the use of information provided herein.",
  },
  {
    id: "third-party-content",
    num: "05",
    title: "Third-Party Content & Advertising",
    content:
      "This website may display advertisements served by Google AdSense and links to third-party websites. These third-party sites have separate and independent privacy policies and terms of use. We have no responsibility or liability for the content, privacy practices, or actions of any linked sites. The inclusion of any link or advertisement does not imply endorsement by us of the site, product, or service being advertised or linked.",
  },
  {
    id: "energy-saving-tips",
    num: "06",
    title: "Energy-Saving Recommendations",
    content:
      "Any energy-saving tips, recommendations, or suggestions provided by this tool are general in nature and intended as a guide only. Actual savings will vary based on your specific appliances, usage habits, home insulation, local climate, and electricity tariff structure. We make no guarantee regarding the savings you will achieve by following any recommendation made by this platform.",
  },
  {
    id: "changes",
    num: "07",
    title: "Changes & Updates",
    content:
      "We reserve the right to modify, update, or remove any content, features, or functionality of this website at any time without prior notice. We also reserve the right to update this Disclaimer at any time. Continued use of the website following any changes constitutes your acceptance of the revised Disclaimer. We encourage you to review this page periodically.",
  },
  {
    id: "contact",
    num: "08",
    title: "Contact Us",
    content:
      "If you have questions, concerns, or feedback regarding this Disclaimer or the accuracy of our calculator, please contact us at support@energycalc.com. While we cannot provide official utility billing advice, we will do our best to address your concerns and improve our tool accordingly.",
  },
];

// ─────────────────────────────────────────────
// Page Component
// ─────────────────────────────────────────────

export default function DisclaimerPage() {
  return (
    <main className="relative overflow-hidden bg-gradient-to-br from-primary/5 via-background to-accent/5 min-h-screen">
      {/* Decorative blobs */}
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute left-1/4 top-1/4 h-72 w-72 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 h-96 w-96 rounded-full bg-accent/10 blur-3xl" />
      </div>
      <Header />

      {/* ── Hero Banner ─────────────────────────────── */}
      <section className="border-b border-border/50 py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
              <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
                <line x1="12" y1="9" x2="12" y2="13" />
                <line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
              Important Notice
            </div>

            <h1 className="text-pretty text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
              Disclaimer &{" "}
              <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                Limitations
              </span>
            </h1>

            <p className="mt-6 text-lg leading-relaxed text-muted-foreground">
              Our electricity bill calculator provides smart estimates to help
              you manage energy costs. Please read the following important
              information about the scope and limitations of our tool.
            </p>

            <div className="mt-6 flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground">
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-primary" />
                Last updated: June 1, 2025
              </span>
              <span className="flex items-center gap-1.5">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-accent" />
                Effective: June 1, 2025
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Body ────────────────────────────────────── */}
      <section className="py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid gap-12 lg:grid-cols-[280px_1fr]">

            {/* Sticky Table of Contents */}
            <aside className="hidden lg:block">
              <div className="sticky top-8 overflow-hidden rounded-2xl border border-border/50 bg-card shadow-lg shadow-primary/5">
                <div className="flex items-center gap-2 border-b border-border/50 px-4 py-3">
                  <div className="h-2.5 w-2.5 rounded-full bg-destructive" />
                  <div className="h-2.5 w-2.5 rounded-full bg-yellow-500" />
                  <div className="h-2.5 w-2.5 rounded-full bg-primary" />
                  <span className="ml-2 text-xs font-medium text-muted-foreground">Contents</span>
                </div>
                <nav className="p-4">
                  <ol className="space-y-1">
                    {sections.map((s, idx) => (
                      <li key={s.id}>
                        <a
                          href={`#${s.id}`}
                          className="group flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-primary/10 hover:text-primary"
                        >
                          <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-secondary text-xs font-semibold text-foreground group-hover:bg-primary/20 group-hover:text-primary">
                            {idx + 1}
                          </span>
                          {s.title}
                        </a>
                      </li>
                    ))}
                  </ol>
                </nav>
              </div>
            </aside>

            {/* Main content */}
            <div className="space-y-10">

              {/* Key limitations – 4-card grid mirrors Features section */}
              <div>
                <h2 className="mb-6 text-xl font-bold text-foreground">Key Limitations at a Glance</h2>
                <div className="grid gap-4 sm:grid-cols-2">
                  {disclaimerCards.map((card) => (
                    <div
                      key={card.title}
                      className="group overflow-hidden rounded-2xl border border-border/50 bg-card p-6 transition-all hover:border-primary/50 hover:shadow-lg hover:shadow-primary/5"
                    >
                      <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-primary/10 to-accent/10 transition-colors group-hover:from-primary/20 group-hover:to-accent/20">
                        {card.icon}
                      </div>
                      <h3 className="mb-2 font-semibold text-foreground">{card.title}</h3>
                      <p className="text-sm leading-relaxed text-muted-foreground">{card.description}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Highlighted warning banner */}
              <div className="overflow-hidden rounded-2xl border border-yellow-500/30 bg-yellow-500/5">
                <div className="flex items-start gap-4 p-6">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-yellow-500/10">
                    <svg className="h-5 w-5 text-yellow-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
                      <line x1="12" y1="9" x2="12" y2="13" />
                      <line x1="12" y1="17" x2="12.01" y2="17" />
                    </svg>
                  </div>
                  <div>
                    <p className="font-semibold text-foreground">This Tool Provides Estimates Only</p>
                    <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
                      Results generated by our calculator are mathematical estimates based on the data
                      you provide and approximate tariff rates. They are not official utility bills.
                      Always consult your electricity provider for accurate billing information.
                    </p>
                  </div>
                </div>
              </div>

              {/* Policy sections */}
              {sections.map((section) => (
                <div
                  key={section.id}
                  id={section.id}
                  className="scroll-mt-8 overflow-hidden rounded-2xl border border-border/50 bg-card shadow-sm transition-shadow hover:shadow-md hover:shadow-primary/5"
                >
                  <div className="flex items-center gap-4 border-b border-border/50 px-6 py-5">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-primary/10 to-accent/10">
                      <span className="text-xs font-bold text-primary">{section.num}</span>
                    </div>
                    <h2 className="text-lg font-semibold text-foreground">{section.title}</h2>
                  </div>
                  <div className="px-6 py-5">
                    <p className="text-sm leading-relaxed text-muted-foreground">{section.content}</p>
                  </div>
                </div>
              ))}

              {/* Bottom stat row */}
              <div className="overflow-hidden rounded-2xl border border-border/50 bg-card px-8 py-6 shadow-sm">
                <div className="flex flex-wrap items-center justify-center gap-8">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-foreground">~95%</div>
                    <div className="text-sm text-muted-foreground">Typical Accuracy</div>
                  </div>
                  <div className="h-8 w-px bg-border" />
                  <div className="text-center">
                    <div className="text-2xl font-bold text-foreground">Estimate</div>
                    <div className="text-sm text-muted-foreground">Not a Bill</div>
                  </div>
                  <div className="h-8 w-px bg-border" />
                  <div className="text-center">
                    <div className="text-2xl font-bold text-foreground">Verify</div>
                    <div className="text-sm text-muted-foreground">With Provider</div>
                  </div>
                  <div className="h-8 w-px bg-border" />
                  <div className="text-center">
                    <div className="text-2xl font-bold text-foreground">Free</div>
                    <div className="text-sm text-muted-foreground">No Obligation</div>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}